---
# Update all packages
- name: Update all packages
  apt:
    update_cache: true
    upgrade: dist

# Install required packages
- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - wget
    - build-essential
    - ca-certificates
    - gnupg
    - lsb-release
    - software-properties-common
    - mc

# Enable IP forwarding for WireGuard VPN
- name: Enable IP forwarding for WireGuard VPN
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: true

- name: Ensure IP forwarding is persistent
  lineinfile:
    path: /etc/sysctl.conf
    regexp: "^net.ipv4.ip_forward"
    line: "net.ipv4.ip_forward=1"
    state: present

# Run docker compose

# - name: Create secrets file
#   copy:
#     content: |
#       HCLOUD_TOKEN={{ lookup('env', 'HCLOUD_TOKEN') }}
#       SSH_KEY_NAME={{ lookup('env', 'SSH_KEY_NAME') }}
#       SSH_PUBLIC_KEY={{ lookup('env', 'SSH_PUBLIC_KEY') }}
#       SUDO_USER={{ lookup('env', 'SUDO_USER') }}
#       SSH_PRIVATE_KEY={{ lookup('env', 'SSH_PRIVATE_KEY') }}
#       TFC_TOKEN={{ lookup('env', 'TFC_TOKEN') }}
#     dest: "/home/{{ ansible_user }}/dev/secrets/.env"
#     owner: "{{ ansible_user }}"
#     group: "{{ ansible_user }}"
#     mode: '0755'
