---
### BACKUPS

# Create a directory for dev snapshot
- name: Create dev snapshot directory
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/tmp_backups/dev_snapshot"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

# Copy the /home/{{ ansible_user }}/dev folder to the snapshot directory
- name: Copy /home/{{ ansible_user }}/dev folder to snapshot directory
  ansible.builtin.shell: |
    rsync -a --delete /home/{{ ansible_user }}/dev/ /home/{{ ansible_user }}/tmp_backups/dev_snapshot/
  args:
    executable: /bin/bash

# Compress the snapshot into a tar.gz file
- name: Create tar.gz backup of dev snapshot
  ansible.builtin.shell: |
    tar -czf "/home/{{ ansible_user }}/tmp_backups/backup_$(date +'%Y%m%d%H%M%S').tar.gz" -C "/home/{{ ansible_user }}/tmp_backups/dev_snapshot/" .
  args:
    executable: /bin/bash

# Rotate backups to keep only the latest 7 tar.gz files
- name: Rotate local backups (keep latest 7 backups)
  ansible.builtin.shell: |
    ls -t /home/{{ ansible_user }}/tmp_backups/backup_*.tar.gz | tail -n +8 | xargs -r rm
  args:
    executable: /bin/bash

# Sync tar.gz backups to storage box
- name: Sync backups to storage box
  command: >
    rsync --progress --delete -e "ssh -i {{ ssh_private_key_path }} -p 23"
    /home/{{ ansible_user }}/tmp_backups/ {{ storage_box_user }}@{{ storage_box_user ~ '.' ~ storage_box_host }}:{{ storage_box_target_dir }}
  register: rsync_output
