---
- name: Bring up Docker Compose services with --remove-orphans
  ansible.builtin.shell: |
    docker-compose up -d --remove-orphans
  args:
    chdir: "{{ compose_path }}/"
  register: compose_output
  changed_when: "'Creating' in compose_output.stdout or 'Starting' in compose_output.stdout"
  failed_when: compose_output.rc != 0
