---
# Create the .env file for secrets
- name: Create secrets file
  copy:
    content: |
      {{ lookup('env', 'COMPOSE_ENV') }}
    dest: "/home/{{ ansible_user }}/dev/compose/.env"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'

- name: Bring up Docker Compose services
  ansible.builtin.shell: |
    docker-compose up -d
  args:
    chdir: "/home/{{ ansible_user }}/dev/compose/"
  register: compose_output
  changed_when: "'Creating' in compose_output.stdout or 'Starting' in compose_output.stdout"
  failed_when: compose_output.rc != 0
