---

# - name: Set executable permissions for all .sh scripts in the scripts folder
#   ansible.builtin.find:
#     paths: "/home/{{ ansible_user }}/dev/compose/scripts/"
#     patterns: "*.sh"
#   register: sh_files

# - name: Change file permissions to readable and executable for all users
#   ansible.builtin.file:
#     path: "{{ item.path }}"
#     mode: '755'  # Set rwxr-xr-x permissions (read, write, execute for owner, read, execute for group and others)
#   with_items: "{{ sh_files.files }}"
#   when: sh_files.matched > 0

# TODO IF NOT FIRST RUN AND SOME file are exists - remove some lines

# Create the .env file for secrets
- name: Create secrets file
  copy:
    content: |
      {{ lookup('env', 'COMPOSE_ENV') }}
    dest: "/home/{{ ansible_user }}/dev/compose/.env"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'

- name: Bring up Docker Compose services
  command: docker-compose up -d
  args:
    chdir: "/home/{{ ansible_user }}/dev/compose/"