version: '3.8'

services:
  # Existing Services
  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    environment:
      CERTBOT_EMAIL: "mystique4u@gmail.com"
    ports:
      - 80:80
      - 443:443
      - 25:25
      - 465:465
      - 587:587
      - 110:110
      - 995:995
      - 143:143
      - 993:993
      - 4190:4190
    volumes:
      - ./nginx/config/domains:/etc/nginx/user_conf.d
      - nginx_secrets:/etc/letsencrypt
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - postgres_odoo
      - odoo
      - front
    networks:
      - main-net

  postgres_odoo:
    image: postgres:latest
    container_name: postgres_odoo
    environment:
      POSTGRES_USER: ${ODOO_DB_USER}
      POSTGRES_PASSWORD: ${ODOO_DB_PASSWORD}
      POSTGRES_DB: ${ODOO_DB_NAME}
      PGDATA: ${ODOO_DB_PGDATA}
    volumes:
      - ./db/postgres_data:/var/lib/postgresql/data
      - ./db/postgresql.conf:/etc/postgresql.conf
      - ./db/pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: postgres -c config_file=/etc/postgresql.conf
    restart: always
    ports:
      - "5433:5432"
    networks:
      - main-net

  odoo:
    image: odoo:latest
    container_name: odoo
    depends_on:
      - postgres_odoo
    environment:
      HOST: postgres_odoo
      USER: ${ODOO_DB_USER}
      PASSWORD: ${ODOO_DB_PASSWORD}
      POSTGRES_DB: ${ODOO_DB_NAME}
    restart: always
    ports:
      - "8069:8069"
      - "8072:8072"
    tty: true
    command: --
    volumes:
      - ./odoo/odoo_data:/var/lib/odoo
      - ./odoo/config:/etc/odoo
      - ./odoo/addons:/mnt/extra-addons
    networks:
      - main-net

  # Mailu Services
  redis:
    container_name: mailu-redis
    image: redis:alpine
    restart: always
    volumes:
      - "./mailu/redis:/data"
    depends_on:
      - resolver
    networks:
      - main-net

  front:
    container_name: mailu-front
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-2024.06}
    restart: always
    env_file: ".env"
    logging:
      driver: journald
      options:
        tag: mailu-front
    networks:
      - main-net
    volumes:
      - "./mailu/certs:/certs"
      - "./mailu/overrides/nginx:/overrides:ro"
    depends_on:
      - resolver

  resolver:
    container_name: mailu-resolver
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-2024.06}
    env_file: ".env"
    logging:
      driver: journald
      options:
        tag: mailu-resolver
    restart: always
    networks:
      main-net:
        ipv4_address: 192.168.20.254

  admin:
    container_name: mailu-admin
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-2024.06}
    restart: always
    env_file: ".env"
    logging:
      driver: journald
      options:
        tag: mailu-admin
    volumes:
      - "./mailu/data:/data"
      - "./mailu/dkim:/dkim"
    depends_on:
      - redis
      - resolver
    networks:
      - main-net

  imap:
    container_name: mailu-imap
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-2024.06}
    restart: always
    env_file: ".env"
    logging:
      driver: journald
      options:
        tag: mailu-imap
    volumes:
      - "./mailu/mail:/mail"
      - "./mailu/overrides/dovecot:/overrides:ro"
    networks:
      - main-net
    depends_on:
      - front

  smtp:
    container_name: mailu-smtp
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-2024.06}
    restart: always
    env_file: ".env"
    logging:
      driver: journald
      options:
        tag: mailu-smtp
    volumes:
      - "./mailu/mailqueue:/queue"
      - "./mailu/overrides/postfix:/overrides:ro"
    networks:
      - main-net
    depends_on:
      - front

  webmail:
    container_name: mailu-webmail
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}webmail:${MAILU_VERSION:-2024.06}
    restart: always
    env_file: ".env"
    logging:
      driver: journald
      options:
        tag: mailu-webmail
    volumes:
      - "./mailu/webmail:/data"
      - "./mailu/overrides/roundcube:/overrides:ro"
    networks:
      - main-net
    depends_on:
      - front

volumes:
  nginx_secrets:

networks:
  main-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.20.0/24
