---
### MOUNT REMOTE DISK
- name: Create ~/mount directory if it doesn't exist
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/storagebox"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Check if the SSHFS mount is already present
  ansible.builtin.command: mountpoint "/home/{{ ansible_user }}/storagebox"
  register: sshfs_mount_check
  changed_when: false
  failed_when: sshfs_mount_check.rc != 0 and sshfs_mount_check.stderr != ""

- name: Mount SSHFS directory if not mounted
  ansible.builtin.shell: |
    sshfs -o IdentityFile={{ ssh_storagebox_pkey_path }} -p 23 u328253@u328253.your-storagebox.de:/home "/home/{{ ansible_user }}/storagebox"
  when: sshfs_mount_check.rc != 0
  become: false  # Ensure this command is run as the ansible_user, not root
