---
### SOME GIT FOLDERS SYNCHRONISATION

# Copy the entire compose directory recursively from the repository to the server
- name: Copy entire compose directory to the server
  synchronize:
    src: ../../../../compose/   # This is the source directory in the repo
    dest: "/home/{{ ansible_user }}/dev/compose/"
    mode: push
    recursive: true
    rsync_opts:
      - "--chmod=F644"

- name: Set write permission for all users on specific folders and their contents
  ansible.builtin.file:
    path: "{{ item }}"
    mode: '0777'
    recurse: true
  loop:
    - "/home/{{ ansible_user }}/dev/compose/odoo"
    - "/home/{{ ansible_user }}/dev/compose/db"

- name: Ensure acme.json has 600 permissions
  file:
    path: "/home/{{ ansible_user }}/dev/compose/traefik/acme.json"
    mode: '0600'

# Copy the entire scripts directory recursively from the repository to the server
- name: Copy entire scripts directory to the server
  synchronize:
    src: ../../../../scripts/
    dest: "/home/{{ ansible_user }}/dev/scripts/"
    mode: push
    recursive: true
    rsync_opts:
      - "--chmod=F777"
