---
- name: Generate backup script from template
  template:
    src: odoo.conf.j2
    dest: "{{ dev_home_path }}/compose/odoo/config/odoo.conf"
    mode: '0755'
    owner: "{{ sudo_user }}"
    group: "{{ sudo_user }}"
