---
- name: Stop Docker Compose services
  community.docker.docker_compose_v2:
    project_src: "/home/{{ ansible_user }}/dev/compose/"
    command: down
    remove_orphans: true

- name: Stop and remove all Docker containers
  community.docker.docker_container_prune:
    force: true

- name: Remove all Docker networks (including unused)
  community.docker.docker_network_prune:
    force: true

- name: Remove all unused Docker images
  community.docker.docker_image_prune:
    all: true
    force: true
