---
- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Enable and start Docker service
  systemd:
    name: docker
    enabled: true
    state: started

- name: Install Docker Compose v2
  get_url:
    url: "https://github.com/docker/compose/releases/download/v2.24.1/docker-compose-{{ ansible_system | lower }}-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Add docker group
  group:
    name: docker
    state: present

- name: Add the current user to the docker group
  user:
    name: "{{ sudo_user }}"
    groups: docker
    append: true

- name: Verify Docker Compose installation
  command: docker-compose version
  register: docker_compose_version
  changed_when: false
  failed_when: docker_compose_version.rc != 0

- name: Display Docker Compose version
  debug:
    msg: "Docker Compose version: {{ docker_compose_version.stdout }}"