---
- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Enable and start Docker service
  systemd:
    name: docker
    enabled: true
    state: started

- name: Install Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ ansible_system | lower }}-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Add docker group
  group:
    name: docker
    state: present

- name: Add the current user to the docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Verify Docker installation
  command: docker --version
  register: docker_version

- name: Display Docker version
  debug:
    msg: "Docker version: {{ docker_version.stdout }}"

- name: Verify Docker Compose installation
  command: docker-compose --version
  register: docker_compose_version

- name: Display Docker Compose version
  debug:
    msg: "Docker Compose version: {{ docker_compose_version.stdout }}"

- name: Stop Docker Compose services
  command: docker-compose down --remove-orphans
  args:
    chdir: "/home/{{ ansible_user }}/dev/compose/"

- name: Stop and remove all Docker containers
  ansible.builtin.shell: |
    docker container prune -f
  args:
    _uses_shell: true

- name: Remove all Docker networks (including unused)
  command: docker network prune -f

- name: Remove all unused Docker images
  command: docker image prune -af
