---
- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Enable and start Docker service
  systemd:
    name: docker
    enabled: true
    state: started

- name: Install Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-{{ ansible_system | lower }}-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Add docker group
  group:
    name: docker
    state: present

- name: Add the current user to the docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true

- name: Verify Docker Compose installation
  ansible.builtin.docker_compose:
    project_src: "/home/{{ ansible_user }}/dev/compose/"
    command: version
  register: docker_compose_version
  changed_when: false
  failed_when: docker_compose_version.rc != 0

- name: Display Docker Compose version
  debug:
    msg: "Docker Compose version: {{ docker_compose_version.stdout }}"

- name: Stop Docker Compose services
  ansible.builtin.docker_compose:
    project_src: "/home/{{ ansible_user }}/dev/compose/"
    command: down
    remove_orphans: true

- name: Stop and remove all Docker containers
  ansible.builtin.docker_container_prune:
    force: true

- name: Remove all Docker networks (including unused)
  ansible.builtin.docker_network_prune:
    force: true

- name: Remove all unused Docker images
  ansible.builtin.docker_image_prune:
    all: true
    force: true
