---
- name: Update OS and setup development environment
  hosts: all
  become: true

  vars:
    storage_box_user: "{{ lookup('env', 'STORAGE_BOX_USER') }}"
    storage_box_host: "{{ lookup('env', 'STORAGE_BOX_HOST') }}"
    ansible_user: "{{ lookup('env', 'SUDO_USER') }}"
    storage_box_target_dir: "backups/hosts/hetznerhost"  # Remote directory
    local_backup_dir: "/home/{{ ansible_user }}/dev/"
    ssh_private_key: "/tmp/storagebox_ssh_key"

  roles:
    - common        # OS updates and base tools
#    - devtools      # Dev tools like Git, Neovim
#    - docker        # Docker and Docker Compose
#    - main-compose       # main compose file
