---
- name: Update OS and setup development environment
  hosts: all
  become: true

  roles:
    - common        # OS updates and base tools
    - devtools      # Dev tools like Git, Neovim
    - docker        # Docker and Docker Compose
    - main-compose       # main compose file
