---
# User Configuration
sudo_user: "{{ lookup('env', 'SUDO_USER') }}"

# Path Configuration
dev_home_path: "/home/{{ sudo_user }}/dev"
compose_path: "{{ dev_home_path }}/compose"
backup_path: "{{ dev_home_path }}/tmp_backups"
storagebox_mount_path: "{{ dev_home_path }}/storagebox"
scripts_path: "{{ dev_home_path }}/scripts"

# Domain Configuration
primary_domain: "{{ lookup('env', 'PRIMARY_DOMAIN', 'mrdevops.pro') }}"
traefik_domain: "traefik.{{ primary_domain }}"
crm_domain: "crm.{{ primary_domain }}"
mail_domain: "mail.{{ primary_domain }}"
portainer_domain: "portainer.{{ primary_domain }}"
traefik_email: "admin@{{ primary_domain }}"

# Storage Box Configuration (SSH/SFTP-based)
storage_box_name: "{{ lookup('env', 'STORAGE_BOX_NAME', 'your-storagebox') }}"
storage_box_user: "{{ lookup('env', 'STORAGE_BOX_USER') }}"
storage_box_host: "{{ lookup('env', 'STORAGE_BOX_HOST') }}"
storage_box_password: "{{ lookup('env', 'STORAGE_BOX_PASSWORD', '') }}"   # optional if using key
storage_box_target_dir: "{{ lookup('env', 'STORAGE_BOX_TARGET_DIR', 'backups/hosts/hetznerhost') }}"

# SSH Key paths for key-based authentication
ssh_storagebox_pkey_path: "/tmp/storagebox_ssh_key"    # Private key for storage box
ssh_private_key_path: "/tmp/private_ssh_key"           # Optional for other SSH tasks

# Local backup directory
local_backup_dir: "{{ backup_path }}"

# SMTP Configuration
smtp_user: "{{ lookup('env', 'SMTP_USER') }}"
smtp_password: "{{ lookup('env', 'SMTP_PASSWORD') }}"
smtp_server: "{{ lookup('env', 'SMTP_SERVER') }}"

# Odoo CRM Configuration
crm_admin_pwd: "{{ lookup('env', 'CRM_ADMIN_PWD') }}"
