---
# storagebox backup
storage_box_user: "{{ lookup('env', 'STORAGE_BOX_USER') }}"
storage_box_host: "{{ lookup('env', 'STORAGE_BOX_HOST') }}"
ansible_user: "{{ lookup('env', 'SUDO_USER') }}"
storage_box_target_dir: "backups/hosts/hetznerhost"  # Remote directory
local_backup_dir: "/home/{{ ansible_user }}/dev/"
ssh_storagebox_pkey_path: "/tmp/storagebox_ssh_key"
ssh_private_key_path: "/tmp/private_ssh_key"
# smptp credentials
smtp_user: "{{ lookup('env', 'SMTP_USER') }}"
smtp_password: "{{ lookup('env', 'SMTP_PASSWORD') }}"
smtp_server: "{{ lookup('env', 'SMTP_SERVER') }}"
# odoo crm specific
crm_admin_pwd: "{{ lookup('env', 'CRM_ADMIN_PWD') }}"