api:
  insecure: false
  dashboard: true
  # Optional: Expose the dashboard on a specific path, e.g. /traefik

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  smtp:
    address: ":25"
  submissions:
    address: ":465"
  imaps:
    address: ":993"
  pop3s:
    address: ":995"
  sieve:
    address: ":4190"

certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@itin.dev
      storage: /etc/traefik/acme.json
      httpChallenge:
        entryPoint: web

providers:
  docker:
    exposedByDefault: false
    swarmMode: true       # Added for Docker Swarm Mode
    watch: true           # Enable watching for changes

metrics:
  prometheus:
    buckets:              # Define Prometheus histogram buckets
      - 0.1
      - 0.3
      - 1.2
      - 5.0

log:
  level: DEBUG            # Set log level to DEBUG
