api:
  insecure: false
  dashboard: true
  # Optional: Expose the dashboard on a specific path, e.g. /traefik

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  smtp:
    address: ":25"
  submissions:
    address: ":465"
  imaps:
    address: ":993"
  pop3s:
    address: ":995"
  sieve:
    address: ":4190"

certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@mrdevops.pro
      storage: /etc/traefik/acme.json
      httpChallenge:
        entryPoint: web

providers:
  docker:
    exposedByDefault: false

tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
      curvePreferences:
        - secp384r1
        - secp521r1